name = "esm-wasm"
type = "javascript"
route = 'esm-wasm'
zone_id = ''
usage_model = ''
workers_dev = true

compatibility_flags = []
compatibility_date = "2022-01-31"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
